# Generated by Django 5.0 on 2024-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_ratingstar_rating_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-01-20'),
            preserve_default=False,
        ),
    ]
