# Generated by Django 5.0 on 2024-01-22 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_reviews_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='shop_review_product_d2a5c4_idx',
            old_name='shop_review_product_636441_idx',
        ),
    ]
