# Generated by Django 5.0 on 2024-02-20 23:21

from django.db import migrations


def add_default_category(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("shop", "Category")
    Category.objects.create(
        name='Laptop',
        slug='laptop',
        short_description='Best laptop',
        image='categories/Laptop-Free-Download-PNG_uANOTgY.png',
    )
    Category.objects.create(
        name='Computer',
        slug='computer',
        short_description='Best 4U',
        image='categories/U0503383.jpg',
    )


def add_default_brand(apps, schema_editor):
    Brand = apps.get_model("shop", "Brand")
    Brand.objects.create(
        name='Asus',
        slug='asus',
        image='brands/asus-logo-transparent_vRkPHHI.png',
    )


def add_default_products(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    Category = apps.get_model("shop", "Category")
    Brand = apps.get_model("shop", "Brand")
    category = Category.objects.get(id=1)
    brand = Brand.objects.get(id=1)
    Product.objects.create(
        category=category,
        brand=brand,
        name='Asus ROG zephyrus',
        slug='asus-rog-zephyrus',
        image='products/2024/02/20/IMG_0362.jpeg',
        description='Some description',
        price='1000',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0007_alter_rating_star_remove_rating_ip_rating_user_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_category),
        migrations.RunPython(add_default_brand),
        migrations.RunPython(add_default_products),
    ]
